hrl_control_bridge:
  ros__parameters:
    control_frequency: 50.0
    joint_names:
      - joint1
      - joint2
      - joint3
      - joint4
    command_topic: /forward_position_controller/commands
    command_interface: position
    u_cmd_topic: /hrl/u_cmd
    goal_topic: /hrl/goal
    obs_topic: /hrl/obs
    reward_topic: /hrl/reward
    done_topic: /hrl/done
    slack_topic: /hrl/slack
    reset_service: /hrl/reset
    success_window: 5
    success_position_tolerance: 0.0175
    success_velocity_tolerance: 0.02
    success_slack_accum: 0.001
    publish_slack: true
    use_cbf: false
    max_episode_steps: 500
    progress_reward_scale: 1.0
    time_penalty: 0.02
    slack_penalty: 5.0
    infeasible_penalty: 5.0
    collision_penalty: 5.0
    joint_position_limits:
      lower: [-2.79, -2.36, -2.36, -2.79]
      upper: [2.79, 2.36, 2.36, 2.79]
    joint_velocity_limits: [2.0, 2.0, 2.5, 3.0]
    initial_position_range:
      lower: [-1.5, -1.0, -1.0, -1.5]
      upper: [1.5, 1.0, 1.0, 1.5]
    random_seed: 1
