version: v1
zones:
  - zone_id: shelf_left
    region_world:
      center_xyz: [0.90, -1.16, 1.22]
      size_xyz: [0.30, 0.30, 0.20]
      yaw: 0.0
    hover_anchor_ids: [hover_shelf_left]

  - zone_id: shelf_right
    region_world:
      center_xyz: [-0.92, -1.16, 1.22]
      size_xyz: [0.30, 0.30, 0.20]
      yaw: 0.0
    hover_anchor_ids: [hover_shelf_right]

  - zone_id: transfer_corridor
    region_world:
      center_xyz: [0.00, -1.16, 1.30]
      size_xyz: [1.70, 0.40, 0.25]
      yaw: 0.0
    hover_anchor_ids: [hover_transfer_mid]

anchors:
  - anchor_id: hover_shelf_left
    zone_id: shelf_left
    pose:
      xyz: [0.86, -1.10, 1.34]
      rpy: [3.14, 0.00, 0.00]

  - anchor_id: hover_shelf_right
    zone_id: shelf_right
    pose:
      xyz: [-0.86, -1.10, 1.34]
      rpy: [3.14, 0.00, 3.14]

  - anchor_id: hover_transfer_mid
    zone_id: transfer_corridor
    pose:
      xyz: [0.00, -1.10, 1.40]
      rpy: [3.14, 0.00, 1.57]
