<?xml version="1.0"?>
<robot name="hrl_manipulator" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="mass" value="1.0"/>
  <xacro:property name="inertia" value="0.01"/>

  <link name="base_link">
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.3 0.2"/>
      </geometry>
      <material name="grey">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 0.3 0.2"/>
      </geometry>
    </collision>
  </link>

  <xacro:macro name="manip_link" params="index length radius">
    <link name="link${index}">
      <inertial>
        <origin xyz="0 0 ${length / 2}"/>
        <mass value="${mass}"/>
        <inertia ixx="${inertia}" ixy="0.0" ixz="0.0" iyy="${inertia}" iyz="0.0" izz="${inertia}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${length / 2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <material name="blue">
          <color rgba="0.1 0.2 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${length / 2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:manip_link index="1" length="0.35" radius="0.04"/>
  <xacro:manip_link index="2" length="0.30" radius="0.035"/>
  <xacro:manip_link index="3" length="0.25" radius="0.03"/>
  <xacro:manip_link index="4" length="0.20" radius="0.025"/>

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-2.79" upper="2.79" velocity="2.0" effort="40.0"/>
    <dynamics damping="0.1" friction="0.0"/>
  </joint>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 0.35" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.36" upper="2.36" velocity="2.0" effort="35.0"/>
    <dynamics damping="0.1" friction="0.0"/>
  </joint>

  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 0.30" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.36" upper="2.36" velocity="2.5" effort="30.0"/>
    <dynamics damping="0.1" friction="0.0"/>
  </joint>

  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0 0.25" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.79" upper="2.79" velocity="3.0" effort="25.0"/>
    <dynamics damping="0.1" friction="0.0"/>
  </joint>

  <link name="tool0">
    <inertial>
      <origin xyz="0 0 0.05"/>
      <mass value="0.2"/>
      <inertia ixx="0.005" ixy="0.0" ixz="0.0" iyy="0.005" iyz="0.0" izz="0.005"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="gripper">
        <color rgba="0.8 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="joint5" type="fixed">
    <parent link="link4"/>
    <child link="tool0"/>
    <origin xyz="0 0 0.20" rpy="0 0 0"/>
  </joint>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find-pkg-share hrl_gazebo)/urdf/ros2_control.yaml</parameters>
    </plugin>
  </gazebo>

  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="joint1">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint2">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint3">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint4">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>
</robot>
